# general
seed: 1
device: 'cuda'
output_path: 'results'

# data
image_path: 'data/street2.jpg'
latents_path: 'latents_forward/street2'

# diffusion
sd_version: '2.1'
guidance_scale: 7.5
n_timesteps: 50
prompt: a photo of a street
negative_prompt: ugly, blurry, black, low res, unrealistic

# pnp injection thresholds [0, 1]
pnp_attn_t: 0.5
pnp_f_t: 0.8

# reference style img
use_style_img: False
style_latents_path : 'latents_forward/street2'

# style injection thresholds [0, 1]
style_attn_t_start: 0.8
style_attn_t_end: 0.9

